name: millers_planet
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter_staggered_grid_view: ^0.7.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/IBMPlexSans/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-BoldItalic.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-ExtraLightItalic.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Italic.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-LightItalic.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-MediumItalic.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-SemiBoldItalic.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Thin.ttf
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-ThinItalic.ttf
    
